### ISSUE TITLE
Feature request: Make all yeti css classes configurable

### ISSUE THREAD

**Issue by Windvis** [miguelcobain/ember-yeti-table#7]
It would be nice if we could choose the default classes that get added to the different components.

**Comment by miguelcobain** [comment]
@Windvis how do you propose to do this?
Would being able to configure the classes prefix be enough?

**Comment by cah-briangantzler** [comment]
I would suggest we do this with a theme. We supply a default theme that contains NO classes, then the user can extend and apply their own theme.

Since we created new head and foot elements, it would be nice if they were merged before doing this so I would not have to update it again.

Working on a pull request. Will let you know when it is completed.

**Comment by miguelcobain** [comment]
@cah-briangantzler what would a "theme" look like (api-wise)?

**Comment by cah-briangantzler** [comment]
I am currently using ember-models-table so I was going to model it off their themes (Just the CSS portion of the theme). A theme would be defined as https://github.com/onechiporenko/ember-models-table/blob/master/addon/themes/bootstrap3.js and could be extended as https://github.com/onechiporenko/ember-models-table/blob/master/addon/themes/ember-bootstrap-v3.js (You only override what you need. In this case they are overriding non-css portions, but you get the point.)

**Comment by cah-briangantzler** [comment]
While I am would not be doing it at this time, you may also note that the theme could be used to give the user the ability to substitute a custom component should you desire that functionality

**Comment by cah-briangantzler** [comment]
You can look at my fork of the repo for the start of a theme, how its implemented, and the tests. https://github.com/bgantzler/ember-yeti-table/blob/theme/addon/themes/yeti-table-default.js


I have the yeti-table classes as constant, with the theme as additional, Alternately the yeti-table classes could be supplied in the default theme and the user replace with their own if needed. This would be useful in the sorting classes as well

**Comment by cah-briangantzler** [comment]
I have most of this complete, working on documentation. Please check my repo if you would like to see what its looking like.

Since the other request has been merged, I will rebase and apply the theme to the new elements as well.

I had seen a while ago Katie saying she was going to review the addon on ember observer but appears she has not gotten to it yet.

**Comment by miguelcobain** [comment]
@cah-briangantzler Some questions:

Is a js class really the best way to hold a collection of css strings (class names)?
We're basically using a class to store key/value pairs, and we could use a normal javascript object for that. `Object.assign()` lets us provide defaults very easy.

The advantage of using objects is interoperability and less api surface. Suddenly, the user could define a theme directly on the template, if they so desired, using the hash helper. Example:

```hbs
<YetiTable
  @data={{data}}
  @theme={{hash
    table="my-custom-class"
    columnSortable="my-custom-sortable-class"
    ...
  }}
as |table|>
```

Another suggestion I have is to look in the global config for such an object. That way users could customize classes once globally.

The theme could be a simple computed like this:
```
@computed('theme')
get processedData() {
  let config = getOwner(this).resolveRegistration('config:environment');
  let configTheme = config['ember-yeti-table'].theme;
  let localTheme = this.get('theme');

  return Object.assign({}, DEFAULT_THEME, configTheme, localTheme);
}
```

Let me know your thoughts.

**Comment by cah-briangantzler** [comment]
I haven't completed it yet, which is why I haven't done a pull request.

If they did the hash on the component itself, they would have to specify every item they wanted. The whole point of a theme is so that you don't have to specify it over and over again on each table (the property is more of a themeOverride? than theme) so it's probably going to be in an external file to import anyway.  And doing the following is just as straightforward as defining the hash with no magic, the theme you get is what you specify, not a mixture of some other classes defined in other places.I personally would never define the theme as a hash in an hbs.

This would be in the users codebase. 

```javascript
import Theme from '';

@computed('theme')
get resultingTheme() {
    return Theme.create({
          table: "newClass"
     });
}

```

The reason for the object is to allow them to extend a default by taking all the values from the default, and adding to them. I was thinking of adding a concatenatedProperties property (much how classNames in components are handled), that would give them the ability to used the default and additively add additional classes, the assign is a replace. 

```javascript
import ThemeDefault from 'ember-yeti-table/themes/yeti-default-theme';

let BootStrapTheme = ThemeDefault.extend({
    table: 'some-bootstrap-class'
});

let bootStrapTheme = BootStrapTheme.create();

// bootStrapTheme.table would equal 'yeti-table some-bootstrap-class'
```
If however you prefer the extend to be solely replace and not additive, yea, a plain old Hash would work.

I like the simplicity of an import and use of a theme, no magic, but I was also going to suggest specifying the theme name in the config and/or could register it with the container as 'theme:yeti-table'. (and the user could register a different theme under that name if they wished to use that instead) although registering the default would require an initializer

There also though was the possibility of extending the theme to more than just classes. If you look at the models-table-theme it was also a way of specifying the messages (you have none yet) and allowing the user to replace certain components with custom ones.

I have not used the resolveRegistration before to get the config, I usually use this addon https://github.com/gmurphey/ember-config-service 

If we start with a plain old hash, it will be harder to convert later if needed. Ember users should be pretty familiar with objects and extending them, although I'm not sure how or if merged and concatenated properties work in class definitions vs extend definitions.

End result, all for the config stuff, several options, just hadn't gotten that far. Just need to know if you insist on a hash for theme. I can do the hash, but I think you might miss out on future possibilities if you go that route.

**Comment by cah-briangantzler** [comment]
Also just thought, since theme is required to be passed down into the components, its the full theme so the below may look like you could do, if you had theme as an override of sorts, but would not end up with the desired output. The resulting theme that got pushed into header.column would be incomplete. While I highly doubt you would change themes midstance, with theme ALWAYS equaling a full theme instead of a partial theme that would be using in an assign, this would work the same way on every component

```javascript
<YetiTable
  @data={{data}}
  @theme={{hash
    table="my-custom-class"
    columnSortable="my-custom-sortable-class"
    ...
  }}
as |table|>
      <table.header theme={{hash
                                   table="my-custom-class"
                                   columnSortable="my-custom-sortable-class"
                                }} as |header|>
       </table.header>
</YetiTable>
```

**Comment by cah-briangantzler** [comment]
Hmmm. concatenatedProperties produces only arrays. I thought that it concatenated strings if they were strings. Second thinking that behaviour

**Comment by cah-briangantzler** [comment]
I took another pass at it. Documentation not complete, coding not complete, but to get an idea.

The theme is still an object, because by doing this I was able to export it in the `app/themes/` directory as `yeti-table`. This will allow the consumer to create a file of the same name in their app, import the default and extend it. This will make it work the same as many classes in ember, yields the same as config, and auto registers it in the container as "theme:yeti-table". Consumer can register a different theme if they wish. 

I also allowed for the theme name to be in the config and on `yeti-table` so if several themes existed in the themes directory they could choose any they want by name.

They can also do the following:

```javascript
@computed('theme')
get resultingTheme() {
   let theme = getOwner(this).lookup('theme:yeti-table');
    return assign(theme, {
          table: "newClass"
     });
}
```

Allowing this to be done as a hash in the HBS could be allowed for, but it I believe it should be a property other than theme, something that indicated this is a subset and will be added to the theme provided or looked up, like themeOverride or something like that.

**Comment by cah-briangantzler** [comment]
Also I am using the @reads and according to 3.0 there is a breaking change renaming the @reads, could we update to 3.0 of decorators?  (4.0 is out as well) https://github.com/ember-decorators/ember-decorators/releases

**Comment by miguelcobain** [comment]
That's a lot to unpack.

> If they did the hash on the component itself, they would have to specify every item they wanted. The whole point of a theme is so that you don't have to specify it over and over again on each table (the property is more of a themeOverride? than theme) so it's probably going to be in an external file to import anyway.

Well, I don't think this is what I was suggesting. The `theme` hash would behave just like you're saying it wouldn't. Users just need to specify what they want to override and not the whole thing. As I illustrated with the computed example, each property would have the assigned `@theme` value, or fallback to the config specified value or fallback to the default theme value.

> There also though was the possibility of extending the theme to more than just classes. If you look at the models-table-theme it was also a way of specifying the messages (you have none yet) and allowing the user to replace certain components with custom ones.

That sounds good. Anything that makes sense can go in that hash as well.

Another thing that I'd like to note is that moving away from EmberObject in favor of JS classes seems to be the general direction Ember is taking. So I think it's positive to not use it on an addon.

To sum it all up, I think the only thing my proposal does not achieve, is that it doesn't "merge" css class names with the default theme, but is that a bad thing?

If people want to keep using the default classes, then can just specify them in the hash, but I think that's not a very interesting use case. The library does not ship any css, so the users will have to write it themselves. It's not a problem if the default classes aren't in the DOM.

More importantly, I think it makes a much simpler api. You don't need to import any classes. You can just use a config hash which people are very used to do in the js world.

Your whole suggestion of registering a theme in the Ember container sounds interesting, but again, it sounds too complicated for a simple addon that doesn't even ship any styles. For what is worth, the name `@theme` seems overloaded at this point. It could even be called `@cssClasses`, but i understand that `@theme` might be more future proof since we might want to add some other stuff there in the future.

I still think my suggestion of using local theme, global config theme and default theme (ordered by "fallback" order) to be a very flexible option, and very easy to understand and teach.
As always, I'm all ears to suggestions and open for discussion.

**Comment by cah-briangantzler** [comment]
There was a lot to go through, but you missed a couple, listed below

Take a look. `DEFAULT_THEME` is provided in the yeti-table component. Not using container, only default, config, provide and assigned together. Can specify theme as hash on yeti-table and will be assigned. NOTE: Specifying theme as hash on any other element is NOT assigned but replaced. If you want that to work too will have to add some code to the init of every element.

I am using the @reads and according to 3.0 there is a breaking change renaming the @reads, could we update to 3.0 of decorators? (4.0 is out as well) https://github.com/ember-decorators/ember-decorators/releases and use the new name instead of having to change later.

Documentation is not complete. WIP

**Comment by miguelcobain** [comment]
> I am using the @reads and according to 3.0 there is a breaking change renaming the @reads, could we update to 3.0 of decorators? (4.0 is out as well) ember-decorators/ember-decorators/releases and use the new name instead of having to change later.

Any such dependency updates are very welcome.

> Take a look. DEFAULT_THEME is provided in the yeti-table component. Not using container, only default, config, provide and assigned together. Can specify theme as hash on yeti-table and will be assigned. 

Awesome. Looks good. I'd just write the DEFAULT_THEME in a separate file `default-theme.js` under the `-private` folder. YetiTable component could re-export it.

> NOTE: Specifying theme as hash on any other element is NOT assigned but replaced. If you want that to work too will have to add some code to the init of every element.

I think we can leave that out. I'm not seeing a very compelling use case for such a mix and match of themes inside a single table. In other words, the `@theme` argument is "private" for child components.

I think you can create a pull request from your theme branch. Makes it easier to provide feedback on the code itself. Thanks for your great work on this. 👍

**Comment by miguelcobain** [comment]
With the merge of #16, this should be possible on master. Need to release this.

**Comment by Windvis** [comment]
Sorry I've been busy so wasn't that active here. Thanks for all the work guys!
