### ISSUE TITLE
Expose processedData

### ISSUE THREAD

**Issue by bgantzler** [miguelcobain/ember-yeti-table#74]
I would like to perform an action that would operate on all visible rows. Currently you expose `visibleRows=processedData.length` on the yield for the table. Would you be opposed to also adding `filteredRows=processedData`. This would allow me to perform an action on all the filtered (visible) rows. Otherwise I would be forced to not use your filtering but instead implement my own filtering and feed the filtered data into yeti in order to have access to it.

**Comment by miguelcobain** [comment]
@bgantzler can you please elaborate on the sort of operation you're trying to make on the visible rows?

**Comment by miguelcobain** [comment]
I see. This makes sense, indeed.

I'm just now regretting that I called `visibleRows` to `processedData.length`.
`visibleRowsNumber` would be more accurate. However, if we do `visibleRows=processedData`, then the user can just write `visibleRows.length` if they're interested on the number.

So, I propose a major bump with this change (since it is a breaking change) and also with the ember-decorators/argument drop + ember-decorators bump.

Does that sound good?

**Comment by miguelcobain** [comment]
Major versions are free and safe. :D

The pagination component doesn't seem to use visibleRows.

**Comment by miguelcobain** [comment]
@cah-briangantzler can you try using `miguelcobain/ember-yeti-table#master`?

I think all these needs were addressed correctly, and I feel the yielded properties naming is much more consistent.

Make sure to check the [CHANGELOG](https://github.com/miguelcobain/ember-yeti-table/blob/master/CHANGELOG.md) to know of all the breaking changes and exactly what happened.
