### ISSUE TITLE
Update to newer version of ember-decorators, use ember-decorators-polyfill to remove deprecations

### ISSUE THREAD

**Issue by bgantzler** [miguelcobain/ember-yeti-table#75]
I am getting a lot of deprecations about using stage 2 decorators and feel they are coming from the older version of ember-decorators. Is this correct?

Any change we can get an updated version of yeti that pulls the decorators provided by ember from ember instead of ember-decorators. Can provide more backward compatibility using ember-decorators-polyfill

**Comment by miguelcobain** [comment]
The problem here is that we can't use stage 1 decorators because `ember-decorators/argument` isn't compatible with them.

There's an [open pull request for that](https://github.com/ember-decorators/argument/pull/109), but it doesn't seem like it is being merged anytime soon.

This is currently a big drawback for the project, especially now with ember octane.

The alternative solution will be to drop ember-decorators/argument from the project. We could migrate to typescript if we want to keep some type safety, but I'm not sure if that would be a 1:1 replacement of ember-decorators/argument.

**Comment by jelhan** [comment]
Would be great to get this resolved cause it's not only about the deprecation warning but is also a blocker for all addons relying on `ember-decorators@v6`. I quickly [asked on discord](https://discordapp.com/channels/480462759797063690/485254664032485395/620927570552029194) and @buschtoens was quite clear that `ember-decorators` should be considered a run-time dependency and that version mismatches might lead to subtle bugs.

**Comment by miguelcobain** [comment]
Can you try depending on `miguelcobain/ember-yeti-table#master` to see if it fixes the problem?

Make sure to check the [CHANGELOG](https://github.com/miguelcobain/ember-yeti-table/blob/master/CHANGELOG.md) to know of all the breaking changes and exactly what happened.

This will be the `v1.0.0` soon.

**Comment by cah-briangantzler** [comment]
Sorry I did not get to this, caught me at a bad time. See 1.0 is out. Hope to use soon
